### ISSUE TITLE
Plugin always scans all records

### ISSUE THREAD

**Issue by gvlx** [SciImage/zotero-attachment-scanner#1]
Expected to scan only shown or selected records.

Always scans the entire library.

**Comment by SciImage** [comment]
A **popup** menu item labeled "Scan Attachments of Selected Items" has been added. 
The caption for the item in the main "Tools" menu has been updated to "Scan All Attachments" to clarify that it applies to all items.

**Comment by SciImage** [comment]
v 0.2.0:
- A **popup** menu item labeled "Scan Attachments of Selected Items" has been added.
- The caption for the item in the main "Tools" menu has been updated to "Scan All Attachments" to clarify that it applies to all items.
