### ISSUE TITLE
Calls from tag style selector buttons seem swapped

### ISSUE THREAD

**Issue by ynedelec3** [SciImage/zotero-attachment-scanner#3]
Great plugin thanks !
I deselected the option scan for no source but no source items are tagged, I I didn't something wrong. My release is 0.2.0
Best regards

**Comment by SciImage** [comment]
Hi Yves,

    Thank you for your feedback!

    I'm not entirely sure what you mean. Are you referring to the three buttons in the preferences window being mixed up, or is it the tags used to label the items that are mixed? I wasn't able to observe either. Could you please provide a detailed description to reproduce the glitch?

    Thanks!

Best,
Wakam

**Comment by ynedelec3** [comment]
Sorry I must have done something wrong during the first scan. After having submitted my initial comment I cleared all tags from this plugin and scanned again. The added tags were in the style of the selected button so the initial comment can be ignored.
Sorry for some confusion.
However, I didn't want "no source" items to be tagged but they were, this is my last and only comment and that may be an issue.
This does matter a lot since the tag can easily be removed.

**Comment by SciImage** [comment]
The "no source" is a separate issue. I will add an option to disable it in the next release.

**Comment by SciImage** [comment]
As suggested, An option was added to disable "no source" tagging.

**Comment by ynedelec3** [comment]
Great ! Thanks a lot
It works perfectly.
