### ISSUE TITLE
Scan cancel does not work in error conditions

### ISSUE THREAD

**Issue by gvlx** [SciImage/zotero-attachment-scanner#5]
As in #4 , there might be _other_ error cases where the cancel action is unable to interrupt the scan.

**Comment by gvlx** [comment]
Please add some instructions on how to debug the case.

**Comment by SciImage** [comment]
Any detail?

**Comment by gvlx** [comment]
On 0.3.0 it now scans my 9047 attachments in less than a minute. :)

Either I've solved the malignant attachment I had, or the code is now more robust.

**Comment by SciImage** [comment]
Great! I don't think the code is now more robust. On my computer, it still scans at 200 items/second.
In fact, due to the new functions and error checking, it should be slower. Although the difference may not be noticeable.
