### ISSUE TITLE
关于优化附件重复附件检查功能建议

### ISSUE THREAD

**Issue by chengwenlong2008** [SciImage/zotero-attachment-scanner#6]
首先感谢开发者的这个插件，给了我们很多便利！
然后，我有一个优化建议，望能采纳！
目前的重复附件检查，一个条目下只要有两个附件就会判定为重复，但是我有的条目下有论文pdf以及它的支撑材料SI文件，这种能否通过附件大小不同或者名称不同，来判定并非重复附件。
以上，感谢！

**Comment by SciImage** [comment]
In this case, the files are duplicates by definition and should be tagged accordingly.
File size is not a reliable criterion. While adding a file name filter is possible, it requires further consideration. It is completely against the purpose of Zotero's auto-rename function.

**Comment by Jansen-Bob** [comment]
It is indeed important to distinguish whether multiple PDF files under an item are duplicates or a collection of original articles, supplementary materials, and peer opinions. Sometimes, there are even multiple images, tables, documents, etc. in the supplementary materials. I really hope to enhance the duplicate attachment checking function to meet potential application needs.

**Comment by SciImage** [comment]
File name masks were introduced in v0.3.0.

**Comment by fredericky123** [comment]
再次提问，现在是基于filename来判断是否重复吗？由于Attanger会自动将所有pdf命名为同一个格式，导致一个正文pdf，一个附录pdf，依然被判定为重复，现在有办法标记只有名称和大小都不同的pdf才会被标记为重复吗？
感谢！

**Comment by SciImage** [comment]
It is really rare for two PDF attachments to have the same size and the same filename.
Please use the available settings "忽略文件名含有这些字串的附件" for intentionally duplicated attachments.

**Comment by fredericky123** [comment]
谢谢，get到这个点了，比如手动给pdf附录命名加上 “appendix”，这样就可以被scanner忽略了
