### ISSUE TITLE
Merge duplicate attachment links

### ISSUE THREAD

**Issue by Jansen-Bob** [SciImage/zotero-attachment-scanner#7]
After an inexplicable synchronization error, the attachment links under each entry became duplicated. The specific situation is that the number of attachments has not changed, but each entry has an additional attachment link pointing to the same attachment. Although it is currently impossible to determine whether PDFs of different sizes are not duplicate entries, it is unknown whether two attachment links can be determined based on the addresses they are linked to. If possible, I hope to add an attachment link merging function to merge attachment links pointing to the same address.

**Comment by SciImage** [comment]
After implementing this function, I realized it could almost certainly lead to file loss when ZotMoov's auto-delete feature is enabled. Other plugins might have the same effect. Therefore, I'm debating whether to include it as a hidden function or exclude it altogether.

**Comment by Jansen-Bob** [comment]
Thank you for trying to solve this problem, and we apologize for any inconvenience caused. Maybe I encountered data damage after a cloud synchronization error. I am wondering if it is possible to identify duplicate attachment links (pointing to the same location), back up a copy first, and then restore the attachment links after deletion, so that the attachment links of literature entries are no longer duplicated.

**Comment by Jansen-Bob** [comment]
This is the situation I encountered
![image](https://github.com/user-attachments/assets/f05408ff-acd2-46ef-950b-bc3a3fa1d32c)

**Comment by SciImage** [comment]
A hidden menu item was added to v0.3.0. See [Technical notes](http://github.com/SciImage/zotero-attachment-scanner/blob/main/README.md#technical-notes) for information and how to show it.
Be extra careful if you have ZotMoov installed. Remember to turn off its "Automatically Delete External Linked Files" option and empty the trash **before** turning it back on.
