### ISSUE TITLE
Non-desired tags when plugin is installled on several PC with synced database

### ISSUE THREAD

**Issue by ynedelec3** [SciImage/zotero-attachment-scanner#8]
Hi
I use Zotero on several Pcs, on which I installed attachment-scanner. My database in synchronized.
It seems that a scan has been operated quickly after the plugin installation (I installed the plugin at the very opening of application)  : non-desired tags  (all three categories and with default simpole format) appeared since I had scanned previously on another PC with non-default options. I guess this scan is triggered by the monitoring option which is set as on by default. If so and if I'm not wrong perhaps would it be more secure to set it as off by default ?
This is not a great problem since tags can be easily removed.
Best regards
Yves

**Comment by SciImage** [comment]
The default is changed to off in v0.3.0. Thanks!

**Comment by ynedelec3** [comment]
Great, thanks
