### ISSUE TITLE
Feature request: scan only selected items or items in view

### ISSUE THREAD

**Issue by gvlx** [SciImage/zotero-attachment-scanner#9]
As explained in #1, this plugin always scans all records.

In large libraries with remote attachments, can be a long and costly operation (cost due to retrieving objects).

There could be an option to only scan the object of the selected items or all the items in the current (filtered) view.

**Comment by SciImage** [comment]
Added since v0.2.0. 
Select items, right-click, and select `Scan Attachments of Selected Items` from the popup menu.
